#!/bin/sh
#
# Configure, build and install an autoconf package for every multilib
# of the cross compiler (except -mshort) into the compiler's sysroot.
#
# usage: cross_build [extra configure arguments]
# TOOL_PREFIX selects the toolchain (default: m68k-atari-mintelf).

TOOL_PREFIX=${TOOL_PREFIX:-m68k-atari-mintelf}
SYSROOT=$(${TOOL_PREFIX}-gcc -print-sysroot) || exit 1
JOBS=-j$(nproc)

for ml in $(${TOOL_PREFIX}-gcc -print-multi-lib | grep -v mshort); do
	# "m68020-60/mfastcall;@m68020-60@mfastcall" -> dir "m68020-60/mfastcall", flags "-m68020-60 -mfastcall"
	dir=${ml%%;*}; dir=${dir#.}
	flags=$(echo "${ml#*;}" | sed 's/@/ -/g; s/^ //')
	libdir=$SYSROOT/usr/lib${dir:+/$dir}
	bindir=$SYSROOT/usr/bin${dir:+/$dir}
	sbindir=$SYSROOT/usr/sbin${dir:+/$dir}

	echo "=== multilib: ${dir:-default} ($flags)"

	PKG_CONFIG_LIBDIR=$libdir/pkgconfig \
	CFLAGS="$CFLAGS -O2 -fomit-frame-pointer $flags" \
	CXXFLAGS="$CXXFLAGS -O2 -fomit-frame-pointer $flags" \
	LDFLAGS="$LDFLAGS $flags" \
	./configure --host=$TOOL_PREFIX --prefix=$SYSROOT/usr \
		--libdir=$libdir --bindir=$bindir --sbindir=$sbindir \
		--disable-shared --enable-static "$@" \
		&& make $JOBS && make install && { make distclean || make clean; } \
		|| exit 1
done
