#!/bin/sh
#
# Wrapper script that calls the real pkg-config with the relocated
# sysroot location.
#
set -e

PLATFORM="m68k-atari-mint"

SYSROOT=$(${PLATFORM}-gcc -print-sysroot)
LIBDIR=${SYSROOT}/usr/lib/$(${PLATFORM}-gcc $CFLAGS $LDFLAGS -print-multi-directory)

export PKG_CONFIG_DIR=
if [ -z ${PKG_CONFIG_LIBDIR+x} ]
then
	export PKG_CONFIG_LIBDIR="${LIBDIR}/pkgconfig"
fi
export PKG_CONFIG_SYSROOT_DIR=

exec pkg-config "$@"
